<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\NexaWork.Domain\NexaWork.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Common/Behaviors/" />
    <Folder Include="Common/Exceptions/" />
    <Folder Include="DTOs/Post/" />
    <Folder Include="Features/Client/Customers/Commands/Create/" />
    <Folder Include="Features/Client/Customers/Commands/Delete/" />
    <Folder Include="Features/Client/Customers/Queries/" />
    <Folder Include="Features/Client/Customers/Queries/GetAll/" />
    <Folder Include="Features/Client/Customers/Queries/GetById/" />
    <Folder Include="Features/Client/Customers/Queries/GetByIdentityId/" />
    <Folder Include="Features/Client/Organization/Commands/" />
    <Folder Include="Features/Client/Organization/Commands/Create/" />
    <Folder Include="Features/Client/Organization/Commands/Delete/" />
    <Folder Include="Features/Client/Organization/Commands/Update/" />
    <Folder Include="Features/Client/Organization/Queries/GetById/" />
    <Folder Include="Features/Client/Post/" />
    <Folder Include="Features/Client/Post/Commands/" />
    <Folder Include="Features/Client/Post/Commands/Create/" />
    <Folder Include="Features/Client/Post/Commands/Delete/" />
    <Folder Include="Features/Client/Post/Commands/Update/" />
    <Folder Include="Features/Client/Post/Queries/" />
    <Folder Include="Features/Client/Post/Queries/GetAll/" />
    <Folder Include="Features/Client/Post/Queries/GetById/" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="14.0.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
